extended example resizing script

diff --git a/examples/resizing/bspc_resize b/examples/resizing/bspc_resize
--- a/examples/resizing/bspc_resize
+++ b/examples/resizing/bspc_resize
@@ -1,38 +1,74 @@
 #!/bin/sh
 # NOTE: This script depends on 'jq' for parsing json!
 # make this script executable and put it somewhere in your PATH
-if [[ "$1" =~ "^(left|down|up|right)$" ]] ; then
-	echo "invalid option"
+if [[ ! "$1" =~ ^(left|down|up|right)$ ]] ; then
+	echo "invalid option" >&2
+	exit 1
+fi
+if [[ ! "$2" =~ ^(-alt)?$ ]] ; then
+	echo "invalid option" >&2
 	exit 1
 fi
 if [[ $(bspc query -T -n | jq -r '.client.state') == "floating" ]] ; then
 	case "$1" in
 	"left")
-		bspc node -z right -20 0
+		if [[ "$2" == "" ]] ; then
+			bspc node -z right -20 0
+		else
+			bspc node -z left -20 0
+		fi
 		;;
 	"down")
-		bspc node -z bottom 0 +20
+		if [[ "$2" == "" ]] ; then
+			bspc node -z bottom 0 +20
+		else
+			bspc node -z top 0 +20
+		fi
 		;;
 	"up")
-		bspc node -z bottom 0 -20
+		if [[ "$2" == "" ]] ; then
+			bspc node -z bottom 0 -20
+		else
+			bspc node -z top 0 -20
+		fi
 		;;
 	"right")
-		bspc node -z right +20 0
+		if [[ "$2" == "" ]] ; then
+			bspc node -z right +20 0
+		else
+			bspc node -z left +20 0
+		fi
 		;;
 	esac
 else
 	case "$1" in
 	"left")
-		bspc node 'parents.!leaf.vertical' -r -0.05
+		if [[ "$2" == "" ]] ; then
+			bspc node 'parents.!leaf.vertical' -r -0.05
+		else
+			bspc node 'any.local.!leaf.vertical' -r -0.05
+		fi
 		;;
 	"down")
-		bspc node 'parents.!leaf.horizontal' -r +0.05
+		if [[ "$2" == "" ]] ; then
+			bspc node 'parents.!leaf.horizontal' -r +0.05
+		else
+			bspc node 'any.local.!leaf.horizontal' -r +0.05
+		fi
 		;;
 	"up")
-		bspc node 'parents.!leaf.horizontal' -r -0.05
+		if [[ "$2" == "" ]] ; then
+			bspc node 'parents.!leaf.horizontal' -r -0.05
+		else
+			bspc node 'any.local.!leaf.horizontal' -r -0.05
+		fi
 		;;
 	"right")
-		bspc node 'parents.!leaf.vertical' -r +0.05
+		if [[ "$2" == "" ]] ; then
+			bspc node 'parents.!leaf.vertical' -r +0.05
+		else
+			bspc node 'any.local.!leaf.vertical' -r +0.05
+		fi
 		;;
 	esac
 fi
